### ISSUE TITLE
Need to fix rlang version in the renv.lock file

### ISSUE THREAD

**Issue by ted9219** [OHDSI/CohortGeneratorModule#21]
I'm trying to install the cohortGeneratorModule using Strategus, I get an error about the installation of dplyr. It seems that we need to fix the version of rlang from 1.0.5 to 1.1.0 in renv.lock file for the requirement.

<img width="970" alt="image" src="https://user-images.githubusercontent.com/42205861/235467530-cf52e714-b357-48a1-a922-2c11e7eb3728.png">

**Comment by ted9219** [comment]
I figured out that many other packages also were out of sync for dplyr. For example vctrs (0.4.1 -> reqired 0.6.0), lifecycle (1.0.2 -> reqired 1.0.3), pillar (1.8.1 -> reqired 1.9.0), tibble(3.1.8 -> required 3.2.0), tidyselect (1.1.2 -> required 1.2.0).

**Comment by anthonysena** [comment]
Fixed in v0.2.0
