### ISSUE TITLE
R version trouble

### ISSUE THREAD

**Issue by msuchard** [OHDSI/CohortGeneratorModule#22]
Some modules (and `Strategus`) require `Rv4.1`, but this one seems to require (see `renv.lock`) `Rv4.2`.   Unfortunately `DatabaseConnector v6.0.0` has trouble installing under `Rv4.1`.   

@pbr6cornell -- should not all modules require the same version of `R`?

**Comment by anthonysena** [comment]
Addressed in all HADES modules, including CohortGeneratorModule v0.2.0. All modules are using the HADES wide lock file which specifies R v4.2.3 which is the version we have adopted in HADES. Additionally, unit tests on the HADES modules now target both R v4.2.3 and the latest version of R (currently v4.3.1) to ensure compatibility as we evaluate new R versions moving forward.
