### ISSUE TITLE
renv lock file not building on Ubuntu

### ISSUE THREAD

**Issue by Thanh-Phuc** [OHDSI/CohortGeneratorModule#28]
When trying to build the renv lock file on Ubuntu, renv wants to install dbplyr, which is not in the lock file and will therefore be the latest version on CRAN, which will depend on other package versions (e.g rlang > 1.0.5, dplyr > 1.1.0) than specified in the lock file.

Also, building building the vctrs package requires rlang 1.10.0, while the lock file specified 1.0.5

@schuemie

**Comment by schuemie** [comment]
@Thanh-Phuc : which version of R are you running?

**Comment by anthonysena** [comment]
Fixed with v0.2.0
