### ISSUE TITLE
Update renv to v1.0

### ISSUE THREAD

**Issue by lhjohn** [OHDSI/CohortGeneratorModule#30]
The current version of renv uses MRAN mirrors, which are being shut down. See here: https://github.com/rstudio/renv/issues/1343

This causes issues when instantiating the renv environment using Strategus. Could you please update renv to version 1.0, which disables MRAN mirrors by default, here https://github.com/OHDSI/CohortGeneratorModule/blob/3c2cb31422f0b6d660fd9b9fe6ad2d2a4876e62c/renv.lock#L403

**Comment by anthonysena** [comment]
Thanks for reporting this @lhjohn - I'm working to update this module (and other Strategus modules + Strategus itself) to use renv 1.0.0.

**Comment by egillax** [comment]
@anthonysena just so you're aware. For me with renv 1.0.0 the auto-snapshotting was turned on by default, which was kind of annoying when I'm updating the deepPLP module. It's fixed in renv 1.0.2

**Comment by anthonysena** [comment]
Thanks @egillax for noting this! I'll make sure to use v1.0.2 as part of these updates. 

For my own ref: https://rstudio.github.io/renv/news/index.html

**Comment by anthonysena** [comment]
Fixed in v0.2.0
