### ISSUE TITLE
Cannot restore renv due to missing binary and source in Posit Package Manager

### ISSUE THREAD

**Issue by lhjohn** [OHDSI/CohortGeneratorModule#36]
By default `renv` uses Posit Package Manager (PPM) to find binaries for the `renv` environment. However, PPM does not provide binary or source for some packages:
```
# Downloading packages -------------------------------------------------------
Warning: failed to find binary for 'MASS 7.3-58.2' in package repositories
Warning: failed to find source for 'MASS 7.3-58.2' in package repositories
Error: failed to retrieve package 'MASS@7.3-58.2'
Traceback (most recent calls last):
8: renv::restore(prompt = FALSE)
7: renv_restore_run_actions(project, diff, current, lockfile, rebuild)
6: retrieve(packages)
5: handler(package, renv_retrieve_impl(package))
4: renv_retrieve_impl(package)
3: renv_retrieve_repos(record)
2: stopf("failed to retrieve package '%s'", renv_record_format_remote(record))
1: stop(sprintf(fmt, ...), call. = call.)
Execution halted
```

Is there any way we can set another mirror? So far no luck with using environmental variables as follows:
- `RENV_CONFIG_PPM_ENABLED=FALSE`
- `RENV_CONFIG_PPM_URL="http://lib.stat.cmu.edu/R/CRAN/"`

What worked to some extend (populate `renv`, but not working to run study yet) is the following inside of the modules:
`options("repos" = "https://cran.r-project.org/")`, then `renv::restore(repos = getOption("repos"))`

**Comment by anthonysena** [comment]
Closing as this has been addressed in OHDSI/Strategus#86.
