### ISSUE TITLE
Bump CirceR reference

### ISSUE THREAD

**Issue by anthonysena** [OHDSI/CohortGeneratorModule#40]
The current ref for CirceR (v1.3.0) is behind on the latest release of circe-be which means that newer cohort JSON documents will not be translated properly.

**Comment by chrisknoll** [comment]
Might want to hold up on this, I have a new erafy logic that I'd like to fold into a hotfix for Circe, and that will also make people re-generate sql from json if they have that, so let me get that task done and then you can proceed here with updating circe ref.
